### ISSUE TITLE
[UI issue] : Add background color to HTML

### ISSUE THREAD

**Issue by TartejBrothers** [singhvivekkumar/portfolio#1]
# Issue 
- When we scroll past the content, we see the background color that is different from the site in the dark mode.
- Trying doing this for dark mode :
```css
body {
        background-color: #1B1B1B;
}
```
- And this for light mode : 
```css
body {
        background-color: #F5F5F5;
}
```
